/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.stanleyseow;

public final class rf24_datarate_e {
  public final static rf24_datarate_e RF24_1MBPS = new rf24_datarate_e("RF24_1MBPS", rf24bcmjavaJNI.RF24_1MBPS_get());
  public final static rf24_datarate_e RF24_2MBPS = new rf24_datarate_e("RF24_2MBPS");
  public final static rf24_datarate_e RF24_250KBPS = new rf24_datarate_e("RF24_250KBPS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static rf24_datarate_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + rf24_datarate_e.class + " with value " + swigValue);
  }

  private rf24_datarate_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private rf24_datarate_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private rf24_datarate_e(String swigName, rf24_datarate_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static rf24_datarate_e[] swigValues = { RF24_1MBPS, RF24_2MBPS, RF24_250KBPS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

