/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.stanleyseow;

public final class rf24_pa_dbm_e {
  public final static rf24_pa_dbm_e RF24_PA_MIN = new rf24_pa_dbm_e("RF24_PA_MIN", rf24bcmjavaJNI.RF24_PA_MIN_get());
  public final static rf24_pa_dbm_e RF24_PA_LOW = new rf24_pa_dbm_e("RF24_PA_LOW");
  public final static rf24_pa_dbm_e RF24_PA_HIGH = new rf24_pa_dbm_e("RF24_PA_HIGH");
  public final static rf24_pa_dbm_e RF24_PA_MAX = new rf24_pa_dbm_e("RF24_PA_MAX");
  public final static rf24_pa_dbm_e RF24_PA_ERROR = new rf24_pa_dbm_e("RF24_PA_ERROR");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static rf24_pa_dbm_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + rf24_pa_dbm_e.class + " with value " + swigValue);
  }

  private rf24_pa_dbm_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private rf24_pa_dbm_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private rf24_pa_dbm_e(String swigName, rf24_pa_dbm_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static rf24_pa_dbm_e[] swigValues = { RF24_PA_MIN, RF24_PA_LOW, RF24_PA_HIGH, RF24_PA_MAX, RF24_PA_ERROR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

