/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.stanleyseow;

public final class rf24_crclength_e {
  public final static rf24_crclength_e RF24_CRC_DISABLED = new rf24_crclength_e("RF24_CRC_DISABLED", rf24bcmjavaJNI.RF24_CRC_DISABLED_get());
  public final static rf24_crclength_e RF24_CRC_8 = new rf24_crclength_e("RF24_CRC_8");
  public final static rf24_crclength_e RF24_CRC_16 = new rf24_crclength_e("RF24_CRC_16");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static rf24_crclength_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + rf24_crclength_e.class + " with value " + swigValue);
  }

  private rf24_crclength_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private rf24_crclength_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private rf24_crclength_e(String swigName, rf24_crclength_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static rf24_crclength_e[] swigValues = { RF24_CRC_DISABLED, RF24_CRC_8, RF24_CRC_16 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

